version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - cp -r dist/ package.json node_modules/ Procfile ./

artifacts:
  files:
    - '**/*'