version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - mkdir -p deploy
      - cp -r dist package.json package-lock.json Procfile node_modules deploy/
      - cd deploy && zip -r ../deploy.zip .

artifacts:
  files:
    - deploy.zip