version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - mkdir -p temp
      - cp -r dist package.json package-lock.json Procfile node_modules temp/
      - cd temp && zip -r ../deploy.zip .
      - rm -rf temp

artifacts:
  files:
    - deploy.zip